# This rule is not used by the project k8s-event-driven-secrets itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over secrets.edsm.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-event-driven-secrets
    app.kubernetes.io/managed-by: kustomize
  name: eventdrivensecret-admin-role
rules:
- apiGroups:
  - secrets.edsm.io
  resources:
  - eventdrivensecrets
  verbs:
  - '*'
- apiGroups:
  - secrets.edsm.io
  resources:
  - eventdrivensecrets/status
  verbs:
  - get
