# This rule is not used by the project k8s-event-driven-secrets itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the secrets.edsm.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-event-driven-secrets
    app.kubernetes.io/managed-by: kustomize
  name: eventdrivensecret-editor-role
rules:
- apiGroups:
  - secrets.edsm.io
  resources:
  - eventdrivensecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.edsm.io
  resources:
  - eventdrivensecrets/status
  verbs:
  - get
