apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: k8s-event-driven-secrets
    app.kubernetes.io/managed-by: kustomize
  name: {{ include "k8s-event-driven-secrets.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-event-driven-secrets.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-event-driven-secrets.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
