---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test-1
  namespace: default
  annotations:
    eventsecrets: '["my-secret-1", "my-secret-2"]'  # Annotation for rollout tracking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu-test
  template:
    metadata:
      labels:
        app: ubuntu-test
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: ["/bin/sh", "-c", "sleep 100000"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test-2
  namespace: default
  annotations:
    eventsecrets: '["db-credentials", "my-secret-2"]'  # Annotation for rollout tracking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu-test
  template:
    metadata:
      labels:
        app: ubuntu-test
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: ["/bin/sh", "-c", "sleep 100000"]
