---
apiVersion: secrets.edsm.io/v1alpha1
kind: EventDrivenSecret
metadata:
  name: my-secret-1
  namespace: default
spec:
  cloudProvider: aws
  cloudProviderOptions:
    region: us-east-1
  secretPath: staging/common-secrets
  targetSecretName: my-secret-1
