---
apiVersion: secrets.edsm.io/v1alpha1
kind: EventDrivenSecret
metadata:
  name: my-secret-1
  namespace: default
spec:
  cloudProvider: aws
  region: eu-west-3
  secretPath: staging/common-secrets
  targetSecretName: my-secret-1
  refreshMode: event
---
apiVersion: secrets.edsm.io/v1alpha1
kind: EventDrivenSecret
metadata:
  name: my-secret-2
  namespace: default
spec:
  cloudProvider: aws
  region: eu-west-3
  secretPath: staging/locker-certificates
  targetSecretName: my-secret-2
  refreshMode: event
---
apiVersion: secrets.edsm.io/v1alpha1
kind: EventDrivenSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  cloudProvider: aws
  region: eu-west-3
  secretPath: staging/backoffice/db-credentials
  targetSecretName: db-credentials
  refreshMode: event